version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.13
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-2-{{ checksum "yarn.lock" }}
      - run:
          name: Set yarn config
          command: echo "yarn-path \".yarn/releases/yarn-sources.js\"" > .yarnrc
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-2-{{ checksum "yarn.lock" }}
          paths:
            - ~/.yarn/berry/cache
      - run:
          name: Check formatting
          command: yarn pretty-quick --check
      - run:
          name: Check tests pass
          command: yarn test
      - run:
          name: Build with rollup
          command: yarn build
      - run:
          name: Check tests pass with build result
          command: yarn test:build
