name: Build, format, and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      YARN_ENABLE_MIRROR: 'false'
      YARN_ENABLE_GLOBAL_CACHE: 'false'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: yarn2-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn2-

      - run: yarn --immutable
      - run: yarn prettier --check .
      - run: yarn test
      - run: yarn build
      - run: yarn test:build
